variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

linux:
  tags:
    - linux
  stage:
    build
  artifacts:
    paths:
    - build/artifacts/
  script:
    #- git submodule update --init --force --recursive
    - APP_VERSION=`grep APP_VERSION quickevent/app/quickevent/src/appversion.h | cut -d\" -f2`
    - ./quickevent/make-dist.sh --src-dir . --app-version ${APP_VERSION} --qt-dir /opt/qt/5.14.1/gcc_64 --work-dir ./build

#win-build:
  #tags:
    #- windows
  #stage:
    #build
  #script:
    #- bash build-win.sh
  #artifacts:
    #paths:
      #- _inno/

#win-deploy:
  #only:
    #- production
  #tags:
    #- windows
  #stage:
    #deploy
  #script:
    #- cmd /Q /C deploy-win.sh
  #environment:
    #name: claudius

